<a href="https://colab.research.google.com/github/YahiaML/World-Cup-Qualifiers-data/blob/main/World_Cup_Qualifiers_data_V_03_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Importing libraries**

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

##**General Scraping Function**

In [2]:
def scrap(link, your_columns):

  # --------- Get the the whole page --------- #

  response = requests.get(str(link))
  data = response.text
  soup = BeautifulSoup(data,"html.parser")

  # --------- Get the the desired data from the page --------- #

  Teams_stats = soup.find_all('tr')

  teams_data = [] # collecting the data in a list 

  for team in Teams_stats:  

    team_data = []
    Team_stats = team.find_all("td")  

    for team in Team_stats:

      team_data.append(team.text) 

    teams_data.append(team_data)

  # --------- Remove empty lists --------- #

  teams_data = [list_ for list_ in teams_data if list_ != []]

  # --------- Remove extra letters in the names --------- #

  for team in teams_data:
    team[0] = team[0][3:]

  # --------- Convert to a dataframe --------- #

  teams_data = pd.DataFrame(teams_data, columns = your_columns )  # inserting columns names

  return teams_data

#**Scraping continents data**

##**Scraping Africa Data**

In [3]:
Africa = scrap("https://fbref.com/en/comps/2/WCQ----CAF-M-Stats", ['Squad',	'MP',	'W',	'D',	'L',	'GF',	'GA',	'GD', 'Pts', 'Notes'])
Africa

            Squad MP  W  D  L  GF  GA   GD Pts           Notes
0         Algeria  6  4  2  0  25   4  +21  14  → Third round
1    Burkina Faso  6  3  3  0  12   4   +8  12
2           Niger  6  2  1  3  13  17   -4   7
3        Djibouti  6  0  0  6   4  29  -25   0
4         Tunisia  6  4  1  1  11   2   +9  13  → Third round
5     Equ. Guinea  6  3  2  1   6   5   +1  11
6          Zambia  6  2  1  3   8   9   -1   7
7      Mauritania  6  0  2  4   2  11   -9   2
8         Nigeria  6  4  1  1   9   3   +6  13  → Third round
9      Cape Verde  6  3  2  1   8   6   +2  11
10        Liberia  6  2  0  4   5   8   -3   6
11            CAR  6  1  1  4   4   9   -5   4
12       Cameroon  6  5  0  1  12   3   +9  15  → Third round
13  Côte d'Ivoire  6  4  1  1  10   3   +7  13
14     Mozambique  6  1  1  4   2   8   -6   4
15         Malawi  6  1  0  5   2  12  -10   3
16           Mali  6  5  1  0  11   0  +11  16  → Third round
17         Uganda  6  2  3  1   3   2   +1   9
18          Kenya  6  1  3  2   4   9   -5   6
19         Rwanda  6  0  1  5   2   9   -7   1
20          Egypt  6  4  2  0  10   4   +6  14  → Third round
21          Gabon  6  2  1  3   7   8   -1   7
22          Libya  6  2  1  3   4   7   -3   7
23         Angola  6  1  2  3   6   8   -2   5
24          Ghana  6  4  1  1   7   3   +4  13  → Third round
25   South Africa  6  4  1  1   6   2   +4  13
26       Ethiopia  6  1  2  3   4   7   -3   5
27       Zimbabwe  6  0  2  4   2   7   -5   2
28        Senegal  6  5  1  0  15   4  +11  16  → Third round
29           Togo  6  2  2  2   5   6   -1   8
30        Namibia  6  1  2  3   5  10   -5   5
31          Congo  6  0  3  3   5  10   -5   3
32        Morocco  6  6  0  0  20   1  +19  18  → Third round
33  Guinea-Bissau  6  1  3  2   5  11   -6   6
34         Guinea  6  0  4  2   5  11   -6   4
35          Sudan  6  0  3  3   5  12   -7   3
36       Congo DR  6  3  2  1   9   3   +6  11  → Third round
37          Benin  6  3  1  2   5   4   +1  10
38       Tanzania  6  2  2  2   6   8   -2   8
39     Madagascar  6  1  1  4   4   9   -5   4

##**Scraping Asia Data**

In [4]:
Asia = scrap("https://fbref.com/en/comps/7/WCQ----AFC-M-Stats", ['Squad',	'MP',	'W',	'D',	'L',	'GF',	'GA',	'GD', 'Pts', 'Notes'])
Asia

              Squad  MP  W  D  L  GF  GA   GD Pts            Notes
0             Syria   8  7  0  1  22   7  +15  21
1          China PR   8  6  1  1  30   3  +27  19
2       Philippines   8  3  2  3  12  11   +1  11
3          Maldives   8  2  1  5   7  20  -13   7
4              Guam   8  0  0  8   2  32  -30   0
5         Australia   8  8  0  0  28   2  +26  24
6            Kuwait   8  4  2  2  19   7  +12  14
7            Jordan   8  4  2  2  13   3  +10  14
8             Nepal   8  2  0  6   4  22  -18   6
9    Chinese Taipei   8  0  0  8   4  34  -30   0
10          IR Iran   8  6  0  2  34   4  +30  18
11             Iraq   8  5  2  1  14   4  +10  17
12          Bahrain   8  4  3  1  15   4  +11  15
13        Hong Kong   8  1  2  5   4  13   -9   5
14         Cambodia   8  0  1  7   2  44  -42   1
15     Saudi Arabia   8  6  2  0  22   4  +18  20
16       Uzbekistan   8  5  0  3  18   9   +9  15
17        Palestine   8  3  1  4  10  10    0  10
18        Singapore   8  2  1  5   7  22  -15   7
19            Yemen   8  1  2  5   6  18  -12   5
20            Qatar   8  7  1  0  18   1  +17  22
21             Oman   8  6  0  2  16   6  +10  18
22            India   8  1  4  3   6   7   -1   7
23      Afghanistan   8  1  3  4   5  15  -10   6
24       Bangladesh   8  0  2  6   3  19  -16   2
25            Japan   8  8  0  0  46   2  +44  24
26       Tajikistan   8  4  1  3  14  12   +2  13
27  Kyrgyz Republic   8  3  1  4  19  12   +7  10
28         Mongolia   8  2  0  6   3  27  -24   6
29          Myanmar   8  2  0  6   6  35  -29   6
30              UAE   8  6  0  2  23   7  +16  18
31          Vietnam   8  5  2  1  13   5   +8  17
32         Malaysia   8  4  0  4  10  12   -2  12
33         Thailand   8  2  3  3   9   9    0   9
34        Indonesia   8  0  1  7   5  27  -22   1
35   Korea Republic   6  5  1  0  22   1  +21  16
36          Lebanon   6  3  1  2  11   8   +3  10
37     Turkmenistan   6  3  0  3   8  11   -3   9
38        Korea DPR   0  0  0  0   0   0    0   0
39        Sri Lanka   6  0  0  6   2  23  -21   0
40         China PR   8  6  1  1  30   3  +27  19
41             Oman   8  6  0  2  16   6  +10  18
42             Iraq   8  5  2  1  14   4  +10  17
43          Vietnam   8  5  2  1  13   5   +8  17
44       Uzbekistan   8  5  0  3  18   9   +9  15
45           Kuwait   8  4  2  2  19   7  +12  14
46       Tajikistan   8  4  1  3  14  12   +2  13
47          Lebanon   6  3  1  3  11  10   +1  10
48          IR Iran  10  8  1  1  15   4  +11  25
49   Korea Republic  10  7  2  1  13   3  +10  23
50              UAE  10  3  3  4   7   7    0  12  → Fourth round
51             Iraq  10  1  6  3   6  12   -6   9
52            Syria  10  1  3  6   9  16   -7   6
53          Lebanon  10  1  3  6   5  13   -8   6
54     Saudi Arabia  10  7  2  1  12   6   +6  23
55            Japan  10  7  1  2  12   4   +8  22
56        Australia  10  4  3  3  15   9   +6  15  → Fourth round
57             Oman  10  4  2  4  11  10   +1  14
58         China PR  10  1  3  6   9  19  -10   6
59          Vietnam  10  1  1  8   8  19  -11   4

##**Scraping Europe Data**

In [5]:
Europe = scrap("https://fbref.com/en/comps/6/WCQ----UEFA-M-Stats",['Squad',	'MP',	'W',	'D',	'L',	'GF',	'GA',	'GD', 'Pts',"Top Team Scorer",	"Goalkeeper", 'Notes'])
Europe = Europe.drop(["Top Team Scorer",	"Goalkeeper"],axis=1)
Europe

                Squad  MP  W  D   L  GF  GA   GD Pts           Notes
0              Serbia   8  6  2   0  18   9   +9  20
1            Portugal   8  5  2   1  17   6  +11  17  → Semi-finals
2     Rep. of Ireland   8  2  3   3  11   8   +3   9
3          Luxembourg   8  3  0   5   8  18  -10   9
4          Azerbaijan   8  0  1   7   5  18  -13   1
5               Spain   8  6  1   1  15   5  +10  19
6              Sweden   8  5  0   3  12   6   +6  15  → Semi-finals
7              Greece   8  2  4   2   8   8    0  10
8             Georgia   8  2  1   5   6  12   -6   7
9              Kosovo   8  1  2   5   5  15  -10   5
10        Switzerland   8  5  3   0  15   2  +13  18
11              Italy   8  4  4   0  13   2  +11  16  → Semi-finals
12   Northern Ireland   8  2  3   3   6   7   -1   9
13           Bulgaria   8  2  2   4   6  14   -8   8
14          Lithuania   8  1  0   7   4  19  -15   3
15             France   8  5  3   0  18   3  +15  18
16            Ukraine   8  2  6   0  11   8   +3  12  → Semi-finals
17            Finland   8  3  2   3  10  10    0  11
18   Bosnia & Herz'na   8  1  4   3   9  12   -3   7
19         Kazakhstan   8  0  3   5   5  20  -15   3
20            Belgium   8  6  2   0  25   6  +19  20
21              Wales   8  4  3   1  14   9   +5  15  → Semi-finals
22     Czech Republic   8  4  2   2  14   9   +5  14
23            Estonia   8  1  1   6   9  21  -12   4
24            Belarus   8  1  0   7   7  24  -17   3
25            Denmark  10  9  0   1  30   3  +27  27
26           Scotland  10  7  2   1  17   7  +10  23  → Semi-finals
27             Israel  10  5  1   4  23  21   +2  16
28            Austria  10  5  1   4  19  17   +2  16
29      Faroe Islands  10  1  1   8   7  23  -16   4
30            Moldova  10  0  1   9   5  30  -25   1
31        Netherlands  10  7  2   1  33   8  +25  23
32             Turkey  10  6  3   1  27  16  +11  21  → Semi-finals
33             Norway  10  5  3   2  15   8   +7  18
34         Montenegro  10  3  3   4  14  15   -1  12
35             Latvia  10  2  3   5  11  14   -3   9
36          Gibraltar  10  0  0  10   4  43  -39   0
37            Croatia  10  7  2   1  21   4  +17  23
38             Russia  10  7  1   2  19   6  +13  22  → Semi-finals
39           Slovakia  10  3  5   2  17  10   +7  14
40           Slovenia  10  4  2   4  13  12   +1  14
41             Cyprus  10  1  2   7   4  21  -17   5
42              Malta  10  1  2   7   9  30  -21   5
43            England  10  8  2   0  39   3  +36  26
44             Poland  10  6  2   2  30  11  +19  20  → Semi-finals
45            Albania  10  6  0   4  12  12    0  18
46            Hungary  10  5  2   3  19  13   +6  17
47            Andorra  10  2  0   8   8  24  -16   6
48         San Marino  10  0  0  10   1  46  -45   0
49            Germany  10  9  0   1  36   4  +32  27
50       N. Macedonia  10  5  3   2  23  11  +12  18  → Semi-finals
51            Romania  10  5  2   3  13   8   +5  17
52            Armenia  10  3  3   4   9  20  -11  12
53            Iceland  10  2  3   5  12  18   -6   9
54      Liechtenstein  10  0  1   9   2  34  -32   1

##**Scraping North America Data**

In [6]:
North_America = scrap("https://fbref.com/en/comps/3/WCQ----CONCACAF-M-Stats",['Squad',	'MP',	'W',	'D',	'L',	'GF',	'GA',	'GD', 'Pts',"Top Team Scorer",	"Goalkeeper", 'Notes'])
North_America = North_America.drop(["Top Team Scorer",	"Goalkeeper"],axis=1)
North_America

                Squad  MP  W  D   L  GF  GA   GD Pts            Notes
0         El Salvador   4  3  1   0  13   1  +12  10  → Second round
1          Montserrat   4  2  2   0   9   4   +5   8
2             Antigua   4  2  1   1   6   5   +1   7
3             Grenada   4  1  0   3   2   5   -3   3
4   US Virgin Islands   4  0  0   4   0  15  -15   0
5              Canada   4  4  0   0  27   1  +26  12  → Second round
6            Suriname   4  3  0   1  15   4  +11   9
7             Bermuda   4  1  1   2   7  12   -5   4
8               Aruba   4  1  0   3   3  19  -16   3
9      Cayman Islands   4  0  1   3   2  18  -16   1
10            Curaçao   4  3  1   0  15   1  +14  10  → Second round
11          Guatemala   4  3  1   0  14   0  +14  10
12               Cuba   4  2  0   2   7   3   +4   6
13        St. Vincent   4  1  0   3   3  16  -13   3
14                BVI   4  0  0   4   0  19  -19   0
15             Panama   4  4  0   0  19   1  +18  12  → Second round
16     Dominican Rep.   4  2  1   1   8   4   +4   7
17           Barbados   4  1  2   1   3   3    0   5
18           Dominica   4  1  1   2   5   4   +1   4
19           Anguilla   4  0  0   4   0  23  -23   0
20              Haiti   3  3  0   0  13   0  +13   9  → Second round
21          Nicaragua   3  2  0   1  10   1   +9   6
22             Belize   3  1  0   2   5   5    0   3
23     Turks & Caicos   3  0  0   3   0  22  -22   0
24          St. Lucia   0  0  0   0   0   0    0   0
25  St. Kitts & Nevis   4  3  0   1   8   2   +6   9  → Second round
26      Trin & Tobago   4  2  2   0   6   1   +5   8
27        Puerto Rico   4  2  1   1  10   2   +8   7
28             Guyana   4  1  0   3   4   8   -4   3
29            Bahamas   4  0  1   3   0  15  -15   1
30             Canada  14  8  4   2  23   7  +16  28             None
31             Mexico  14  8  4   2  17   8   +9  28             None
32      United States  14  7  4   3  21  10  +11  25             None
33         Costa Rica  14  7  4   3  13   8   +5  25             None
34             Panama  14  6  3   5  17  19   -2  21             None
35            Jamaica  14  2  5   7  12  22  -10  11             None
36        El Salvador  14  2  4   8   8  18  -10  10             None
37           Honduras  14  0  4  10   7  26  -19   4             None

##**Scraping South America Data**

In [7]:
South_America = scrap("https://fbref.com/en/comps/4/WCQ----CONMEBOL-M-Stats",['Squad',	'MP',	'W',	'D',	'L',	'GF',	'GA',	'GD', 'Pts',"Top Team Scorer",	"Goalkeeper", 'Notes'])
South_America = South_America.drop(["Top Team Scorer",	"Goalkeeper"],axis=1)
South_America

,Squad,MP,W,D,L,GF,GA,GD,Pts,Notes
0,Brazil,17,14,3,0,40,5,+35,45,
1,Argentina,17,11,6,0,27,8,+19,39,
2,Uruguay,18,8,4,6,22,22,0,28,
3,Ecuador,18,7,5,6,27,19,+8,26,
4,Peru,18,7,3,8,19,22,-3,24,→ WCQ — Inter-confederation play-offs (M)
5,Colombia,18,5,8,5,20,19,+1,23,
6,Chile,18,5,4,9,19,26,-7,19,
7,Paraguay,18,3,7,8,12,26,-14,16,
8,Bolivia,18,4,3,11,23,42,-19,15,
9,Venezuela,18,3,1,14,14,34,-20,10,

# x

In [8]:
response = requests.get('https://fbref.com/en/comps/2/WCQ----CAF-M-Stats')
data = response.text
soup = BeautifulSoup(data,"html.parser")

In [22]:
Teams_stats = soup.find_all('div',{"class":"match-summary"})

In [24]:
team_data = []
for team in Teams_stats:
  team = team.text.split()
  team_data.append(team[1:3])

team_data

[['Mozambique', '3–0'],
 ['Tanzania', '2–2'],
 ['Liberia', '3–2'],
 ['Namibia', '4–1'],
 ['Angola', '3–1'],
 ['Togo', '3–1'],
 ['Sudan', '3–1'],
 ['Rwanda', '10–0'],
 ['Guinea-Bissau', '3–1'],
 ['Ethiopia', '1–1'],
 ['Equ.', 'Guinea'],
 ['Zimbabwe', '3–2'],
 ['Djibouti', '2–1'],
 ['Malawi', '1–0'],
 ['Ghana', '1–1'],
 ['Cameroon', '2–2'],
 ['Tunisia', '1–0'],
 ['Senegal', '1–1'],
 ['Morocco', '5–2']]

In [25]:
x = '10–0'

In [26]:
"matchup-note"
Notes = soup.find_all('div',{"class":"matchup-note"})

In [28]:
teams_notes = []
for note in Notes:

  teams_notes.append(note.text)

teams_notes

['Mozambique  won on aggregate score over two legs and advance to Second round.',
 'Tanzania  won on penalty kicks following extra time and advance to Second round.',
 'Liberia  won on aggregate score over two legs and advance to Second round.',
 'Namibia  won on aggregate score over two legs and advance to Second round.',
 'Angola  won on aggregate score over two legs and advance to Second round.',
 'Togo  won on aggregate score over two legs and advance to Second round.',
 'Sudan  won on aggregate score over two legs and advance to Second round.',
 'Rwanda  won on aggregate score over two legs and advance to Second round.',
 'Guinea-Bissau  won on aggregate score over two legs and advance to Second round.',
 'Ethiopia  won on away goals, after aggregate score was tied and advance to Second round.',
 'Equ. Guinea  won on aggregate score over two legs and advance to Second round.',
 'Zimbabwe  won on aggregate score over two legs and advance to Second round.',
 'Djibouti  won on aggregate score over two legs and advance to Second round.',
 'Malawi  won on aggregate score over two legs and advance to Second round.',
 'Ghana  won on away goals, after aggregate score was tied.',
 'Cameroon  won on away goals, after aggregate score was tied.',
 'Tunisia  won on aggregate score over two legs.',
 'Senegal  won on penalty kicks following extra time.',
 'Morocco  won on aggregate score over two legs.']

In [41]:
for i in range(len(team_data)):
  team_data[i].append(teams_notes[i])
  print(team_data[i])

['Mozambique', '3–0', 'Mozambique  won on aggregate score over two legs and advance to Second round.']
['Tanzania', '2–2', 'Tanzania  won on penalty kicks following extra time and advance to Second round.']
['Liberia', '3–2', 'Liberia  won on aggregate score over two legs and advance to Second round.']
['Namibia', '4–1', 'Namibia  won on aggregate score over two legs and advance to Second round.']
['Angola', '3–1', 'Angola  won on aggregate score over two legs and advance to Second round.']
['Togo', '3–1', 'Togo  won on aggregate score over two legs and advance to Second round.']
['Sudan', '3–1', 'Sudan  won on aggregate score over two legs and advance to Second round.']
['Rwanda', '10–0', 'Rwanda  won on aggregate score over two legs and advance to Second round.']
['Guinea-Bissau', '3–1', 'Guinea-Bissau  won on aggregate score over two legs and advance to Second round.']
['Ethiopia', '1–1', 'Ethiopia  won on away goals, after aggregate score was tied and advance to Second round.']
['Equ.', 'Guinea', 'Equ. Guinea  won on aggregate score over two legs and advance to Second round.']
['Zimbabwe', '3–2', 'Zimbabwe  won on aggregate score over two legs and advance to Second round.']
['Djibouti', '2–1', 'Djibouti  won on aggregate score over two legs and advance to Second round.']
['Malawi', '1–0', 'Malawi  won on aggregate score over two legs and advance to Second round.']
['Ghana', '1–1', 'Ghana  won on away goals, after aggregate score was tied.']
['Cameroon', '2–2', 'Cameroon  won on away goals, after aggregate score was tied.']
['Tunisia', '1–0', 'Tunisia  won on aggregate score over two legs.']
['Senegal', '1–1', 'Senegal  won on penalty kicks following extra time.']
['Morocco', '5–2', 'Morocco  won on aggregate score over two legs.']

In [42]:
team_data

[['Mozambique',
  '3–0',
  'Mozambique  won on aggregate score over two legs and advance to Second round.'],
 ['Tanzania',
  '2–2',
  'Tanzania  won on penalty kicks following extra time and advance to Second round.'],
 ['Liberia',
  '3–2',
  'Liberia  won on aggregate score over two legs and advance to Second round.'],
 ['Namibia',
  '4–1',
  'Namibia  won on aggregate score over two legs and advance to Second round.'],
 ['Angola',
  '3–1',
  'Angola  won on aggregate score over two legs and advance to Second round.'],
 ['Togo',
  '3–1',
  'Togo  won on aggregate score over two legs and advance to Second round.'],
 ['Sudan',
  '3–1',
  'Sudan  won on aggregate score over two legs and advance to Second round.'],
 ['Rwanda',
  '10–0',
  'Rwanda  won on aggregate score over two legs and advance to Second round.'],
 ['Guinea-Bissau',
  '3–1',
  'Guinea-Bissau  won on aggregate score over two legs and advance to Second round.'],
 ['Ethiopia',
  '1–1',
  'Ethiopia  won on away goals, after aggregate score was tied and advance to Second round.'],
 ['Equ.',
  'Guinea',
  'Equ. Guinea  won on aggregate score over two legs and advance to Second round.'],
 ['Zimbabwe',
  '3–2',
  'Zimbabwe  won on aggregate score over two legs and advance to Second round.'],
 ['Djibouti',
  '2–1',
  'Djibouti  won on aggregate score over two legs and advance to Second round.'],
 ['Malawi',
  '1–0',
  'Malawi  won on aggregate score over two legs and advance to Second round.'],
 ['Ghana', '1–1', 'Ghana  won on away goals, after aggregate score was tied.'],
 ['Cameroon',
  '2–2',
  'Cameroon  won on away goals, after aggregate score was tied.'],
 ['Tunisia', '1–0', 'Tunisia  won on aggregate score over two legs.'],
 ['Senegal', '1–1', 'Senegal  won on penalty kicks following extra time.'],
 ['Morocco', '5–2', 'Morocco  won on aggregate score over two legs.']]